M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-05-14T17:49:16+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-14T17:49:16+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X114.0Y-129.7
X167.9Y-70.9
M30
